apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: agnetz
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: primary-secrets
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: agnetz/app
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: agnetz/app
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: agnetz/app
        property: POSTGRES_DB
    - secretKey: DATABASE_URL
      remoteRef:
        key: agnetz/app
        property: DATABASE_URL
