apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agnetz
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
