---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: agnetz-secrets
  namespace: agnetz-prod
spec:
  encryptedData:
    API_KEY: AgAktfRMVFUhlgOx8m3L73jil4GBzP5eEcvXacQMwf65Cg0jnMGYu8QTO5OJt+K0xxofP7Q+cn4TY9eUpgi9ECy+4E2hgsrUBQGtSmQmCgmWJ4Wr1VbVYjYGpam5WogtWnFlIKkyHfEADDF8Q+cqErqkzg/uFrnqx9P93aFuPVe/dzXSi55csag8Rw88MiiVrMLbvHRU4yyBLTw/9hAA24p6kn/SbkoRTgUdx6mwm7eQbjDskuz/P1hdQo38mwkhPxcRwYrCMB9krCUkDkM+ii/E2cEqFr2nojSpIXrkXDc9tDHQ2kST21BBCoSygFU48LTOWiQn5stBYq+qvoIvnEdtJXn5MmEX3oXCkzqsYBU5Paz5iRqVaX/leeC7uFZFDOkEEFRZq0u5vBHx7ZNObFBRVdGri5ynYT6mv/5DzgJRGr0wq9vLoaVVzjrRD7dR+04eezb9B0M3TY9B/OHF9dP212w8BXkOwXD5Q2DW186C75xfW2JEeisXq+tFJP0IcUpm95L1EB1ABQERHgiNdijrBq4d/38VmTttuCYGRclcajUxcrh1A7HuBVkoYzhIbEQPy9LHKVh5g3y741Ty+/Kc0N5Apx0qxl8sI1Z5p/vimOuOIC+fImRx5CEyeOGbbL67rZ8UjvyypyYl1x4Z42dU/Owz2BybjLM/JMV7bIMO40t54e+l67yQVa4Mez0x1q6a5mBpUIQoJeYs
    DATABASE_URL: AgBj+TUOPTygHOz7l7pfQmuELkKijXNhF4VJK2ubNmF2aHvKTRnf5mAT9pt+8Z8cL3akXLGw5F/2OPp5uxoAxcziC7RYhaNBfViKnysnz045FCZSUHle6zEXUTSxvMaLDZftHoih2OTp3HwlPpou0G/9zzMP6ql7sk1re8WQrhL4+TlmKq1ElxNdmsoIstjar5kk2a6fDp7P6BYRKhhVlmudHuD9byLk5ZnxQpKbi6Hd+LmsjoWbOCV0Nr0xHgnAORjz1aR7fuQFlEEVdQT/oXyxrXdBBCmfsVv21gZNL41HtdAUWe2zQ2JSlEPOSJP5eSDiYSbYtSNrra4538VNUrrDlQXjDG7sZiwReQiO3LAnt7Fkrp1d3Pj2G3rGDRat0uoZPjV+KVMAE+94mDJKSAe4E+uyJh7M2BNfuyzuFiFPcMac5rzhU4ByKVWfSrJzT4mLDwwlhj8OXCRIbt+4ZMvSu+a9QkSxY0qqkKruyKRY5NABDclZmHipG6gP3ZTfUGGr8qQOrlX7L/1K5DSnE68yzq6d3dSFd0o+KyDObSXaqdSTfFdQL0i9HuK5rL8x5qZfFWBLP8SG4HxHkPkjdb+gBGTSRy0nzCud5iRE6HNdne5ZE/1ZW28kPzbfXgTkV3WYFs1L6vNLixnGGMi2FVI6FoW7R2SAjZ7QWKGzkOSZmSaslk/6DLTRRaDEC3dID8BEI2Wp7spp9hjzp10eXRWcewwe7U9C4XXZvym8OBxn79CuQUU5AFVk7lkwM/TfMF3OAwTwQCE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: agnetz-secrets
      namespace: agnetz-prod
    type: Opaque
