apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: agnetz-prod
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:QX6h5vloABmdVPzXDrHt+dqdQ4sIqQCne9/xjloFvEMslmEz+LCbr9ebSSfkOtJrfHzcGyw/,iv:jZpXjd2x4YVSSniDcA2BBYCW0dMwJx5O/sxgNn5T1Xk=,tag:TMvOKlgQoKV8EuGUi/SAlw==,type:str]
    API_KEY: ENC[AES256_GCM,data:seEoDH8WG7GwSCmlmiw6WBDsfQ63TftoNranA3RdQf8u+/F+BRNGHt6fcHmJ8DAKeqv6fet3b7bJMHWuIiIW2g==,iv:jYGA9oqME0AslwlDIlJarhRZ20kg1h/fAMckiDfvEQg=,tag:2G/WsPvOlMtkS2s7C+6FWQ==,type:str]
sops:
    age:
        - recipient: age1d5quqwq6s5ydqzfvqn2vny75lw6r0mahynacdhfrqmc33fphma2sxyery7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eUE5QnFvRlM3dnhaWHYy
            T2JjZU9FNEovM3o5a0Y1VlJUZGNDMyszbFZrCmZxMVhtZTVSd1RDODJUZ29PMWJa
            bjkwK1l2eFZEcG9mSFkyNmJ1aTRvWjQKLS0tIG1NMUJsajJ4YktwR2s2V0diNmww
            NjZXTk11Mld4RTVObjc1OGVEWEZSRm8KrXFRyo5hLLzVDvO2nndAMC2RIN2GzuQ1
            o09QLOQWofTAE3MEBd141j6BGx8VWtHu13elSEgD0JUR+C6/b6isug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T11:42:15Z"
    mac: ENC[AES256_GCM,data:OpfYdn2ZzIE/0FwbhohS7Ji8yXBL2+RLtlPUSqKoEqYj8dWXn05Dljn7d4EpjXZtwIlTnwWsxwP3PuhDHdX+3u3+sr7VbKlsT+QhQ36l92X1uLRYCQN1ACSvswX/rVrL2bqL6cFJPjbyMOvc2re7ih+NE7LBDzTXQQ7etmb50l0=,iv:MIXhIfHR3/KjDhqZc6qVuyLMOQH/T3ggvf2RaPKggTk=,tag:RYl05u0vS5+BO2U36NACGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
