apiVersion: v1
kind: Secret
metadata:
    name: agnetz-secrets
    namespace: agnetz-prod
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:NndgLJuSUwp2kNA/DSrAWLn8ZiY8dSskMkRJFsiJgGkBMjIoWls3z388gss7a2IWB0fO3VlB,iv:5NKQxuwRYGdLlvtAj5uuVrSrnXKT5TlladNkEDwetOo=,tag:Kr0hgq2OsVI+t844OBHEaQ==,type:str]
    API_KEY: ENC[AES256_GCM,data:holZ7MIWt0eQJQ==,iv:ZDeZOUFY1lGFSqby9+E5NbfdBmVClPvkDrIQqIZcgSQ=,tag:wFxgwJjYnyzHKwAheRJIbw==,type:str]
sops:
    age:
        - recipient: age1mzpvq6ylq5ndneck3qgjn3s65rzy6ekey0kxjce9sfy047nsygwq9fs9da
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbWxWYkdybXA2QlAyMmpV
            RUFZa0JSbnI4a2kyOE9hU2hpSXNMcytRRWp3CjNXVnJ4SERrS3lvZXlUcjJBOGc3
            a3FpNDJYWVRsOE0rR3N2TzNTZ1NSTk0KLS0tIFA0clExVnZpTnJFcFR5SVJrdG9o
            VS9ydEoyTCtuN3gxdmdCTDNhMEI1bE0KXpFupLHDrM3qOYN2VGpH2PAPJLudDUXj
            wPTMwkrEPvsCne5mYpdXWqnoX58pimoPD1ZhkVNRbAoorZuCeiyzXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T18:34:59Z"
    mac: ENC[AES256_GCM,data:a7SMY6nLeE0qYqWCd3/LZSIY3qkJHDkZZhv0uMJTpUdkz5FEWGSLbcsUNgEXhj6uC1jkJnk0T82BRy6Clw8h0itQ/qTffYiBVD8rrg0NPNlWCX9GFviEyUZUICfcxTuWOZxaR75GXjwQVY/7cxktRAwSjnh+Vh6XFNI2d7hJBOE=,iv:vDKluf5CJh6RMn/tyBRrWS0jOp5OZxN3b1oloP+L768=,tag:Lb+SnWbWt0tkFo77N6Oaig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
