apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: agnetz-prod
spec:
  encryptedData:
    DATABASE_URL: REPLACE_ME
    API_KEY: REPLACE_ME
  template:
    metadata:
      name: app-secrets
      namespace: agnetz-prod
    type: Opaque
