apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generated-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ID377585/Agnetz-IA.git
    targetRevision: HEAD
    path: k8s/apps/generated-app
  destination:
    server: https://kubernetes.default.svc
    namespace: agnetz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
