apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: agnetz-staging
type: Opaque
stringData:
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: dev
  POSTGRES_DB: devdb
  DATABASE_URL: postgresql://dev:dev@postgres:5432/devdb?schema=public
  API_KEY: "REPLACE_ME"
