apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: agnetz-staging
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:1i2KvLMnC83KyZ52RKwOZg2J9qQ2E7jG97ewNuJpK0MEmEnu6SxvBSGNJQ2opySxoI6H1bdw,iv:lreptvIh2L8SS/r/RAKCInxGHlP9n/64KdMaxCsgYQ0=,tag:G+yKp/Fu+CPlBkjK/d6Row==,type:str]
    API_KEY: ENC[AES256_GCM,data:ehBzfZTbYNVfIEvLf5Y0zI4o56JaA3p1BhyWuHxeqQvO/hVwrFs4u1f0dt8lcdxkZDiS61hJrPJqLjeqOflfMA==,iv:JWkEzwB/6AXNWmcM/9V3XHOUDMbUhqrO1w9rlF0zmCQ=,tag:FUVatsX/uoprnp23fzS0lQ==,type:str]
sops:
    age:
        - recipient: age1d5quqwq6s5ydqzfvqn2vny75lw6r0mahynacdhfrqmc33fphma2sxyery7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTFlNNy9ZMGI5bnBVVm13
            TjVCZURuc2QwbE5aamlTZVAxODVGalFqYkFRClpaTElhOEQwY2JKT09aTkY1SENm
            aHpSWUxydjdPbFZyNGVYUU9hNEhyUUUKLS0tIHcxUHo4VzBBbWVKakIwdllpS1ZN
            T0xNYU9XbDBmUTJYdHh6eHVsTnArODQK8tl2TVFQw6g5J9OyYDFCEma55LTsomC4
            UoZEibgKPtz2b523PtxLlV0phOqFrQ8ZdNTQdqrtcFXxEiIMKGaisg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T11:42:15Z"
    mac: ENC[AES256_GCM,data:BKrYl7PdEfeF3AojZejVgzxbwDruHXXIfyibjU9LQWunvsylXrYqThxlHUZLshrlusoSHW4jwBG2u96S9tlFnUMhlGGDZ9i/a1EOZfb9BL19NErNR/o1GgzmrknDi1D8XmSo7mqraIxHBRUyykIFH0mck5v/6AUJhQWWC60nA98=,iv:8u9a6vcLMn18J60qH5XMgyMEE+6szXnXV8SWBqlXk6Q=,tag:NtG4ruG8l29gLp7gdBWf3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
